begin;

alter table public.counterparties
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists display_name text,
  add column if not exists email text,
  add column if not exists pec text,
  add column if not exists phone text,
  add column if not exists mobile_phone text,
  add column if not exists organization text,
  add column if not exists job_title text,
  add column if not exists address text,
  add column if not exists city text,
  add column if not exists postal_code text,
  add column if not exists province text,
  add column if not exists notes text,
  add column if not exists needs_review boolean not null default false,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid,
  add column if not exists delete_reason text;

update public.counterparties
set display_name = coalesce(
  nullif(btrim(name), ''),
  'Controparte #' || id::text
)
where display_name is null or btrim(display_name) = '';

create index if not exists counterparties_studio_deleted_at_idx
  on public.counterparties (studio_id, deleted_at);

create or replace function public.normalize_counterparty_name(p_value text)
returns text
language sql
immutable
parallel safe
as $$
  select btrim(
    regexp_replace(
      translate(
        lower(btrim(coalesce(p_value, ''))),
        'àáâäãåèéêëìíîïòóôöõùúûüç',
        'aaaaaaeeeeiiiiooooouuuuc'
      ),
      '[^a-z0-9]+',
      ' ',
      'g'
    )
  );
$$;

update public.counterparties
set normalized_name = public.normalize_counterparty_name(display_name)
where normalized_name is null or btrim(normalized_name) = '';

create index if not exists counterparties_studio_normalized_name_idx
  on public.counterparties (studio_id, normalized_name);

create table if not exists public.case_counterparties (
  id bigint generated by default as identity primary key,
  studio_id uuid not null references public.studios(id),
  case_id bigint not null references public.cases(id),
  counterparty_id bigint not null references public.counterparties(id),
  created_at timestamptz not null default now(),
  created_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  delete_reason text
);

create index if not exists case_counterparties_studio_case_idx
  on public.case_counterparties (studio_id, case_id);

create index if not exists case_counterparties_counterparty_idx
  on public.case_counterparties (counterparty_id);

create unique index if not exists case_counterparties_active_unique_idx
  on public.case_counterparties (case_id, counterparty_id)
  where deleted_at is null;

-- Preserve every existing relational link. No column on cases is changed.
insert into public.case_counterparties (
  studio_id,
  case_id,
  counterparty_id
)
select
  current_case.studio_id,
  current_case.id,
  current_case.counterparty_id
from public.cases as current_case
join public.counterparties as current_counterparty
  on current_counterparty.id = current_case.counterparty_id
 and current_counterparty.studio_id = current_case.studio_id
where current_case.counterparty_id is not null
on conflict do nothing;

-- Convert raw-only names into reviewable records. Existing counterparties are
-- reused by normalized name and neither legacy field on cases is overwritten.
with raw_candidates as (
  select distinct on (
    current_case.studio_id,
    public.normalize_counterparty_name(current_case.defendant_name_raw)
  )
    current_case.studio_id,
    btrim(current_case.defendant_name_raw) as display_name,
    public.normalize_counterparty_name(current_case.defendant_name_raw)
      as normalized_name
  from public.cases as current_case
  where current_case.counterparty_id is null
    and nullif(btrim(current_case.defendant_name_raw), '') is not null
  order by
    current_case.studio_id,
    public.normalize_counterparty_name(current_case.defendant_name_raw),
    current_case.id
)
insert into public.counterparties (
  studio_id,
  name,
  display_name,
  normalized_name,
  counterparty_type,
  active,
  needs_review
)
select
  candidate.studio_id,
  candidate.display_name,
  candidate.display_name,
  candidate.normalized_name,
  'da_classificare',
  true,
  true
from raw_candidates as candidate
where candidate.normalized_name <> ''
  and not exists (
    select 1
    from public.counterparties as existing_counterparty
    where existing_counterparty.studio_id = candidate.studio_id
      and (
        existing_counterparty.normalized_name = candidate.normalized_name
        or public.normalize_counterparty_name(existing_counterparty.name) =
          candidate.normalized_name
      )
  )
on conflict do nothing;

insert into public.case_counterparties (
  studio_id,
  case_id,
  counterparty_id
)
select
  current_case.studio_id,
  current_case.id,
  matched_counterparty.id
from public.cases as current_case
join lateral (
  select existing_counterparty.id
  from public.counterparties as existing_counterparty
  where existing_counterparty.studio_id = current_case.studio_id
    and (
      existing_counterparty.normalized_name =
        public.normalize_counterparty_name(current_case.defendant_name_raw)
      or public.normalize_counterparty_name(existing_counterparty.name) =
        public.normalize_counterparty_name(current_case.defendant_name_raw)
    )
  order by
    (existing_counterparty.deleted_at is null) desc,
    existing_counterparty.id
  limit 1
) as matched_counterparty on true
where current_case.counterparty_id is null
  and nullif(btrim(current_case.defendant_name_raw), '') is not null
on conflict do nothing;

create or replace function public.enforce_counterparty_soft_delete_permission()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.deleted_at is distinct from new.deleted_at
    and auth.uid() is not null
    and not exists (
      select 1
      from public.user_permissions
      where user_id = auth.uid()
        and can_edit_clients = true
    )
  then
    raise exception
      'Non disponi del permesso per eliminare o ripristinare le controparti.'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

drop trigger if exists counterparties_soft_delete_permission
  on public.counterparties;

create trigger counterparties_soft_delete_permission
before update of deleted_at on public.counterparties
for each row
execute function public.enforce_counterparty_soft_delete_permission();

create or replace function public.enforce_counterparty_write_permission()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null
    and not exists (
      select 1
      from public.profiles as current_profile
      join public.user_permissions as current_permissions
        on current_permissions.user_id = current_profile.id
      where current_profile.id = auth.uid()
        and current_profile.studio_id = new.studio_id
        and current_profile.active = true
        and current_profile.deleted_at is null
        and current_permissions.can_edit_clients = true
    )
  then
    raise exception
      'Non disponi del permesso per modificare le controparti di questo studio.'
      using errcode = '42501';
  end if;

  if tg_op = 'UPDATE' and old.studio_id is distinct from new.studio_id then
    raise exception 'Non è possibile spostare una controparte tra studi.'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

drop trigger if exists counterparties_write_permission
  on public.counterparties;

create trigger counterparties_write_permission
before insert or update on public.counterparties
for each row
execute function public.enforce_counterparty_write_permission();

alter table public.counterparties enable row level security;

drop policy if exists counterparties_studio_select
  on public.counterparties;

create policy counterparties_studio_select
on public.counterparties
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as current_profile
    join public.user_permissions as current_permissions
      on current_permissions.user_id = current_profile.id
    where current_profile.id = auth.uid()
      and current_profile.studio_id = counterparties.studio_id
      and current_profile.active = true
      and current_profile.deleted_at is null
      and (
        current_permissions.can_view_clients = true
        or current_permissions.can_view_cases = true
      )
  )
);

drop policy if exists counterparties_studio_insert
  on public.counterparties;

create policy counterparties_studio_insert
on public.counterparties
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles as current_profile
    join public.user_permissions as current_permissions
      on current_permissions.user_id = current_profile.id
    where current_profile.id = auth.uid()
      and current_profile.studio_id = counterparties.studio_id
      and current_profile.active = true
      and current_profile.deleted_at is null
      and current_permissions.can_edit_clients = true
  )
);

drop policy if exists counterparties_studio_update
  on public.counterparties;

create policy counterparties_studio_update
on public.counterparties
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles as current_profile
    join public.user_permissions as current_permissions
      on current_permissions.user_id = current_profile.id
    where current_profile.id = auth.uid()
      and current_profile.studio_id = counterparties.studio_id
      and current_profile.active = true
      and current_profile.deleted_at is null
      and current_permissions.can_edit_clients = true
  )
)
with check (
  exists (
    select 1
    from public.profiles as current_profile
    join public.user_permissions as current_permissions
      on current_permissions.user_id = current_profile.id
    where current_profile.id = auth.uid()
      and current_profile.studio_id = counterparties.studio_id
      and current_profile.active = true
      and current_profile.deleted_at is null
      and current_permissions.can_edit_clients = true
  )
);

grant select, insert, update on public.counterparties to authenticated;

alter table public.case_counterparties enable row level security;

drop policy if exists case_counterparties_select
  on public.case_counterparties;

create policy case_counterparties_select
on public.case_counterparties
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as current_profile
    join public.user_permissions as current_permissions
      on current_permissions.user_id = current_profile.id
    where current_profile.id = auth.uid()
      and current_profile.studio_id = case_counterparties.studio_id
      and current_profile.active = true
      and current_profile.deleted_at is null
      and (
        current_permissions.can_view_cases = true
        or current_permissions.can_view_clients = true
      )
  )
);

create or replace function public.set_case_counterparties(
  p_case_id bigint,
  p_counterparty_ids bigint[] default '{}'::bigint[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_studio_id uuid;
  current_counterparty_id bigint;
  normalized_ids bigint[];
  existing_link_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Utente non autenticato.' using errcode = '42501';
  end if;

  select current_case.studio_id
  into current_studio_id
  from public.cases as current_case
  join public.profiles as current_profile
    on current_profile.studio_id = current_case.studio_id
   and current_profile.id = auth.uid()
   and current_profile.active = true
   and current_profile.deleted_at is null
  join public.user_permissions as current_permissions
    on current_permissions.user_id = current_profile.id
   and current_permissions.can_edit_cases = true
  where current_case.id = p_case_id
    and current_case.deleted_at is null;

  if current_studio_id is null then
    raise exception 'Pratica non trovata o modifica non autorizzata.'
      using errcode = '42501';
  end if;

  select coalesce(array_agg(distinct requested_id), '{}'::bigint[])
  into normalized_ids
  from unnest(coalesce(p_counterparty_ids, '{}'::bigint[]))
    as requested(requested_id)
  where requested_id is not null;

  if exists (
    select 1
    from unnest(normalized_ids) as requested(requested_id)
    left join public.counterparties as requested_counterparty
      on requested_counterparty.id = requested_id
     and requested_counterparty.studio_id = current_studio_id
     and (
       requested_counterparty.deleted_at is null
       or exists (
         select 1
         from public.case_counterparties as historical_link
         where historical_link.case_id = p_case_id
           and historical_link.counterparty_id = requested_id
           and historical_link.deleted_at is null
       )
     )
    where requested_counterparty.id is null
  ) then
    raise exception
      'Una o più controparti non esistono, sono eliminate o appartengono a un altro studio.'
      using errcode = '22023';
  end if;

  update public.case_counterparties
  set
    deleted_at = now(),
    deleted_by = auth.uid(),
    delete_reason = 'Scollegata dalla pratica'
  where case_id = p_case_id
    and studio_id = current_studio_id
    and deleted_at is null
    and not (counterparty_id = any(normalized_ids));

  foreach current_counterparty_id in array normalized_ids
  loop
    select existing_link.id
    into existing_link_id
    from public.case_counterparties as existing_link
    where existing_link.case_id = p_case_id
      and existing_link.counterparty_id = current_counterparty_id
    order by
      (existing_link.deleted_at is null) desc,
      existing_link.created_at desc,
      existing_link.id desc
    limit 1;

    if existing_link_id is null then
      insert into public.case_counterparties (
        studio_id,
        case_id,
        counterparty_id,
        created_by
      )
      values (
        current_studio_id,
        p_case_id,
        current_counterparty_id,
        auth.uid()
      );
    else
      update public.case_counterparties
      set
        deleted_at = null,
        deleted_by = null,
        delete_reason = null
      where id = existing_link_id;
    end if;

    existing_link_id := null;
  end loop;
end;
$$;

revoke all on function public.set_case_counterparties(bigint, bigint[])
  from public;
grant execute on function public.set_case_counterparties(bigint, bigint[])
  to authenticated;

create or replace function public.save_case_with_counterparties(
  p_case jsonb,
  p_counterparty_ids bigint[] default '{}'::bigint[],
  p_case_id bigint default null
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  authorized_studio_id uuid;
  requested_studio_id uuid;
  requested_client_id bigint;
  existing_client_id bigint;
  saved_case_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Utente non autenticato.' using errcode = '42501';
  end if;

  if p_case is null or jsonb_typeof(p_case) <> 'object' then
    raise exception 'I dati della pratica non sono validi.'
      using errcode = '22023';
  end if;

  begin
    requested_studio_id := nullif(p_case ->> 'studio_id', '')::uuid;
    requested_client_id := nullif(p_case ->> 'client_contact_id', '')::bigint;
  exception
    when invalid_text_representation then
      raise exception 'Studio o cliente non validi.' using errcode = '22023';
  end;

  if requested_studio_id is null or requested_client_id is null then
    raise exception 'Studio e cliente sono obbligatori.'
      using errcode = '22023';
  end if;

  if p_case_id is null then
    select current_profile.studio_id
    into authorized_studio_id
    from public.profiles as current_profile
    join public.user_permissions as current_permissions
      on current_permissions.user_id = current_profile.id
     and current_permissions.can_edit_cases = true
    where current_profile.id = auth.uid()
      and current_profile.active = true
      and current_profile.deleted_at is null;

    if authorized_studio_id is null
      or authorized_studio_id is distinct from requested_studio_id
    then
      raise exception 'Creazione della pratica non autorizzata per questo studio.'
        using errcode = '42501';
    end if;
  else
    select current_case.studio_id, current_case.client_contact_id
    into authorized_studio_id, existing_client_id
    from public.cases as current_case
    join public.profiles as current_profile
      on current_profile.studio_id = current_case.studio_id
     and current_profile.id = auth.uid()
     and current_profile.active = true
     and current_profile.deleted_at is null
    join public.user_permissions as current_permissions
      on current_permissions.user_id = current_profile.id
     and current_permissions.can_edit_cases = true
    where current_case.id = p_case_id
      and current_case.deleted_at is null;

    if authorized_studio_id is null then
      raise exception 'Pratica non trovata o modifica non autorizzata.'
        using errcode = '42501';
    end if;

    if requested_studio_id is distinct from authorized_studio_id then
      raise exception 'Non è possibile spostare una pratica tra studi.'
        using errcode = '42501';
    end if;
  end if;

  if not exists (
    select 1
    from public.contacts as requested_client
    where requested_client.id = requested_client_id
      and requested_client.studio_id = authorized_studio_id
      and (
        requested_client.deleted_at is null
        or (
          p_case_id is not null
          and requested_client.id = existing_client_id
        )
      )
  ) then
    raise exception
      'Il cliente non esiste, è eliminato o appartiene a un altro studio.'
      using errcode = '22023';
  end if;

  if p_case_id is null and exists (
    select 1
    from unnest(coalesce(p_counterparty_ids, '{}'::bigint[]))
      as requested(requested_id)
    left join public.counterparties as requested_counterparty
      on requested_counterparty.id = requested_id
     and requested_counterparty.studio_id = authorized_studio_id
     and requested_counterparty.deleted_at is null
    where requested_id is null or requested_counterparty.id is null
  ) then
    raise exception
      'Una o più controparti non esistono, sono eliminate o appartengono a un altro studio.'
      using errcode = '22023';
  end if;

  if p_case_id is null then
    insert into public.cases (
      studio_id,
      client_contact_id,
      counterparty_id,
      title,
      case_type,
      claimant_name_raw,
      defendant_name_raw,
      court_type,
      court_city,
      section,
      rg_number,
      judge_name,
      status,
      opening_date,
      description,
      notes,
      needs_review,
      active
    )
    values (
      authorized_studio_id,
      requested_client_id,
      (coalesce(p_counterparty_ids, '{}'::bigint[]))[1],
      nullif(p_case ->> 'title', ''),
      coalesce(nullif(p_case ->> 'case_type', ''), 'causa_lavoro'),
      nullif(p_case ->> 'claimant_name_raw', ''),
      nullif(p_case ->> 'defendant_name_raw', ''),
      nullif(p_case ->> 'court_type', ''),
      nullif(p_case ->> 'court_city', ''),
      nullif(p_case ->> 'section', ''),
      nullif(p_case ->> 'rg_number', ''),
      nullif(p_case ->> 'judge_name', ''),
      coalesce(nullif(p_case ->> 'status', ''), 'nuova'),
      nullif(p_case ->> 'opening_date', '')::date,
      nullif(p_case ->> 'description', ''),
      nullif(p_case ->> 'notes', ''),
      coalesce((p_case ->> 'needs_review')::boolean, false),
      coalesce((p_case ->> 'active')::boolean, true)
    )
    returning id into saved_case_id;
  else
    update public.cases
    set
      client_contact_id = requested_client_id,
      title = nullif(p_case ->> 'title', ''),
      case_type = coalesce(
        nullif(p_case ->> 'case_type', ''),
        case_type
      ),
      claimant_name_raw = nullif(p_case ->> 'claimant_name_raw', ''),
      court_type = nullif(p_case ->> 'court_type', ''),
      court_city = nullif(p_case ->> 'court_city', ''),
      section = nullif(p_case ->> 'section', ''),
      rg_number = nullif(p_case ->> 'rg_number', ''),
      judge_name = nullif(p_case ->> 'judge_name', ''),
      status = coalesce(nullif(p_case ->> 'status', ''), status),
      opening_date = nullif(p_case ->> 'opening_date', '')::date,
      description = nullif(p_case ->> 'description', ''),
      notes = nullif(p_case ->> 'notes', ''),
      needs_review = coalesce(
        (p_case ->> 'needs_review')::boolean,
        needs_review
      ),
      active = coalesce((p_case ->> 'active')::boolean, active)
    where id = p_case_id
      and studio_id = authorized_studio_id
      and deleted_at is null
    returning id into saved_case_id;

    if saved_case_id is null then
      raise exception 'La pratica non è stata aggiornata.'
        using errcode = 'P0001';
    end if;
  end if;

  -- PostgreSQL esegue l'intera RPC in un'unica transazione: qualsiasi errore
  -- nella sincronizzazione annulla anche l'insert o l'update della pratica.
  perform public.set_case_counterparties(
    saved_case_id,
    coalesce(p_counterparty_ids, '{}'::bigint[])
  );

  return saved_case_id;
exception
  when invalid_text_representation or datetime_field_overflow then
    raise exception 'Uno o più dati della pratica non hanno un formato valido.'
      using errcode = '22023';
end;
$$;

revoke all on function public.save_case_with_counterparties(
  jsonb,
  bigint[],
  bigint
) from public;
grant execute on function public.save_case_with_counterparties(
  jsonb,
  bigint[],
  bigint
) to authenticated;

grant select on public.case_counterparties to authenticated;

commit;
